// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxDdDMDyYzT0havT-3STx4mKoQlkSksmk',
    appId: '1:618816893913:web:aaf05930538506a2f21fc8',
    messagingSenderId: '618816893913',
    projectId: 'onlyone-48ae8',
    authDomain: 'onlyone-48ae8.firebaseapp.com',
    storageBucket: 'onlyone-48ae8.firebasestorage.app',
    measurementId: 'G-DGQ1DJSXB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGJFVwfyKEdrHY3un_BrDqcOOGodeb9o',
    appId: '1:618816893913:android:2e8265ab3626c6fff21fc8',
    messagingSenderId: '618816893913',
    projectId: 'onlyone-48ae8',
    storageBucket: 'onlyone-48ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7BqQ1VXpwx5fJxUjNLVOhoGuXCxjHXkY',
    appId: '1:618816893913:ios:d716da0d531a56aaf21fc8',
    messagingSenderId: '618816893913',
    projectId: 'onlyone-48ae8',
    storageBucket: 'onlyone-48ae8.firebasestorage.app',
    iosClientId:
        '618816893913-rjdrcaonpfgedek5vrokkc7vtb7hc8bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlyoneFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7BqQ1VXpwx5fJxUjNLVOhoGuXCxjHXkY',
    appId: '1:618816893913:ios:d716da0d531a56aaf21fc8',
    messagingSenderId: '618816893913',
    projectId: 'onlyone-48ae8',
    storageBucket: 'onlyone-48ae8.firebasestorage.app',
    iosClientId:
        '618816893913-rjdrcaonpfgedek5vrokkc7vtb7hc8bo.apps.googleusercontent.com',
    iosBundleId: 'com.bubble.OnlyOneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxDdDMDyYzT0havT-3STx4mKoQlkSksmk',
    appId: '1:618816893913:web:c200d126e596b79af21fc8',
    messagingSenderId: '618816893913',
    projectId: 'onlyone-48ae8',
    authDomain: 'onlyone-48ae8.firebaseapp.com',
    storageBucket: 'onlyone-48ae8.firebasestorage.app',
    measurementId: 'G-PLHRG44LSY',
  );
}
